blank_issues_enabled: false

contact_links:
  - name: Open a Issue
    url: https://code.forgejo.org/LinuxUserGD/gdscript-transpiler-bin/issues/new
    about: Open a new issue on code.forgejo.org.