class_name __Main__
## GDScript Transpiler Script
##
## Wrapper script using transpiler for converting any GDScript code to Python
## (including the transpiler script)
## using search-and-replace syntax
##
##

## Runs once when executed, prints different output to console depending on argument
func _ready() -> void:
	DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_MINIMIZED)
	var __init__ = preload("__init__.gd").new()
	for arg in OS.get_cmdline_args():
		if arg == "version":
			version_info()
			return
		if arg == "help":
			help()
			return
		if arg == "test=vector2":
			run_vector2()
			return
		if arg == "benchmark":
			run_benchmark()
			return
		if arg == "test=parser":
			run_parser()
			return
		var path_format_arg: String = "format="
		if arg.begins_with(path_format_arg) and arg.ends_with(".gd"):
			const format: bool = true
			const comp: bool = false
			start(arg, format, comp, __init__.package_name)
			const ESCAPE: String = ''
			printraw(ESCAPE + "[2K\r")
			return
		var path_binary_arg: String = "gen_api="
		if arg.begins_with(path_binary_arg):
			arg = arg.replace(path_binary_arg, "")
			gen_api(arg)
			return
		var path_exp_arg: String = "exp="
		if arg.begins_with(path_exp_arg):
			start_exp(arg, __init__.package_name)
			print("")
			return
		var path_tree_arg: String = "tree="
		if arg.begins_with(path_tree_arg):
			start_tree(arg, __init__.package_name)
			return
		var compile_arg = "compile="
		if arg.begins_with(compile_arg) and arg.ends_with(".gd"):
			const format: bool = true
			const comp: bool = true
			start(arg, format, comp, __init__.package_name)
			const ESCAPE: String = ''
			printraw(ESCAPE + "[2K\r")
			return
		var setup_arg: String = "setup="
		if arg.begins_with(setup_arg):
			setup(__init__.setuptools_min_ver, __init__.package_name, __init__.author, __init__.author_email, __init__.project_url, __init__.download_url, __init__.documentation_url, __init__.source_url, __init__.tracker_url, __init__.description, __init__.proj_license)
			return
	help()
	return

## Function for generating GDScript files from extension api
func gen_api(program: String) -> void:
	var application = Application.new()
	var version = application.execute(program, ["--headless", "--quit"])
	version = version[0].split("\n")[0]
	var info: Dictionary = Engine.get_version_info()
	var major: int = info.get("major")
	var minor: int = info.get("minor")
	var patch: int = info.get("patch")
	var status: String = info.get("status")
	var build: String = info.get("build")
	var id: String = info.get("hash")
	var compat: String = "v"
	compat += str(major)
	compat += "."
	compat += str(minor)
	compat += "."
	if (patch != 0):
		compat += str(patch)
		compat += "."
	compat += status
	compat += "."
	compat += build
	compat += "."
	compat += id.left(9)
	var col = version.split(" ")
	if col.size() < 3:
		print("Invalid godot4 executable")
		return
	if compat != col[2]:
		print("Invalid godot4 executable")
		return
	print("Generating GDScript files from extension api...")
	application.execute(program, ["--headless", "--dump-extension-api"])
	save_extension_api()

func save_extension_api() -> void:
	var transpiler = Transpiler.new()
	var content: Array = transpiler.read("extension_api.json").split("\n")
	save_enum_from_api(content, "Variant.Operator")
	save_enum_from_api(content, "Variant.Type")
	save_enum_from_api(content, "Key")

func save_enum_from_api(content: Array, search: String) -> void:
	var script_name: String = search.to_lower()
	script_name = script_name.replace(".", "_")
	var sl: int = script_name.length()
	var classn: String = script_name[0].to_upper()
	classn += script_name.right(sl-1)
	var out: String = "## GDScript Transpiler Properties Class"
	out += "\n\n"
	out += "# Autogenerated class (gen_api)"
	out += "\n"
	out += "# See https://raw.githubusercontent.com/godotengine/godot-cpp/master/gdextension/extension_api.json"
	out += "\n\n"
	out += "class_name %s" % classn
	out += "\n\n"
	var line: int = 0
	var l: int = content.size()
	for i in range(0, l):
		if content[i].contains(search):
			line = i+1
			break
	for i in range(line, l):
		if content[i].ends_with("["):
			line = i+1
			break
	for i in range(line, l):
		if content[i].contains("name"):
			var res: String = content[i].split(" ")[1]
			res = res.split('"')[1]
			out += "const %s: int = " % res
			continue
		if content[i].contains("value"):
			var res: String = content[i].split(" ")[1]
			out += res
			out += "\n"
			continue
		if content[i].ends_with("]"):
			break
		else:
			continue
	var pathstr = "gdsbin/" + script_name
	var path: String = "res://" + pathstr + ".gd"
	var transpiler = Transpiler.new()
	transpiler.save(path, out)

## Function for compiling python script (by path)
func compile(arg: String) -> void:
	var path_end: String = arg.split("=")[1]
	var args = path_end.split(".")
	var c: int = args.size()
	var pathstr: String = ""
	for path_str in args:
		c -= 1
		if c != 0:
			pathstr += path_str + "."
	var nopt: Array = []
	nopt.append(pathstr + "py")
	nopt.append("--onefile")
	nopt.append("--no-progressbar")
	nopt.append("--show-scons")
	nopt.append("--quiet")
	nopt.append("--remove-output")
	nopt.append("--lto=yes")
	nopt.append("--deployment")
	nopt.append("--static-libpython=auto")
	nopt.append("--clang")
	nopt.append("--assume-yes-for-downloads")
	print()
	print("Compiling " + pathstr + "py...")
	print("Info: Running " + "'" + " ".join(nopt) + "'")
	var application = Application.new()
	application.execute_pipe("python3.13", ['-c',nopttoarg(nopt)])

func nopttoarg(nopt: Array) -> String:
	var opts: Array = []
	opts.append("import nuitka.__main__")
	opts.append("import sys")
	var args: String = "sys.argv=[sys.executable,"
	for opt in nopt:
		args += "'%s'," % opt
	args += "]"
	opts.append(args)
	# AttributeError: module '__main__' has no attribute '__file__'. Did you mean: '__name__'?
	opts.append("sys.modules['__main__'].__file__=sys.modules['__main__'].__name__")
	opts.append("nuitka.__main__.main()")
	var out: String = ";".join(opts)
	return out

## Tokenize script (by path)
func start_exp(arg: String, _package_name: String) -> void:
	var path_end: String = arg.split("=")[1]
	var path: String = "res://" + path_end
	var transpiler = Transpiler.new()
	var content: String = transpiler.read(path)
	var tokenizer = Tokenizer.new()
	var con: Array = content.split("\n")
	var unit: Array = []
	for line in con:
		var tokens : Array = tokenizer.tokenize(line)
		unit.append(tokens)
	var ast = Ast.new()
	var root = Root.new()
	var ast_res = ast.ast(0, unit.size(), 0, root, unit, con)
	var parsertree = Parsertree.new()
	var string_res = parsertree.printpt(ast_res, 0)
	print(string_res)

## Tokenize script (by path)
func start_tree(arg: String, _package_name: String) -> void:
	var path_end: String = arg.split("=")[1]
	var path: String = "res://" + path_end
	var transpiler = Transpiler.new()
	var content: String = transpiler.read(path)
	var tokenizer = Tokenizer.new()
	var con: Array = content.split("\n")
	var unit: Array = []
	for line in con:
		var tokens : Array = tokenizer.tokenize(line)
		unit.append(tokens)
	var ast = Ast.new()
	var root = Root.new()
	var ast_res = ast.ast(0, unit.size(), 0, root, unit, con)
	var parsertree = Parsertree.new()
	var e = parsertree.printtree(ast_res, 0)
	var string_res = parsertree.printrec(e, "")
	print(string_res)

## Tokenize script (by path)
func token_tree(arg: String, _package_name: String) -> void:
	var path_end: String = arg.split("=")[1]
	var path: String = "res://" + path_end
	var transpiler = Transpiler.new()
	var content: String = transpiler.read(path)
	var tokenizer = Tokenizer.new()
	var con: Array = content.split("\n")
	var e: Dictionary = {}
	for i in range(0, con.size()):
		var l: Dictionary = {}
		var tokens : Array = tokenizer.tokenize(con[i])
		for ii in range(0, tokens.size()):
			l["Token"+str(ii)] = {"id": {str(tokens[ii].id): null}, "value": {tokens[ii].value: null}}
		e["line "+str(i)] = l
	var parsertree = Parsertree.new()
	var string_res = parsertree.printrec(e, "")
	print(string_res)

## Function for saving setup.py
func setup(setuptools_min_ver: int, package_name: String, author: String, author_email: String, project_url: String, download_url: String, documentation_url: String, source_url: String, tracker_url: String, description: String, proj_license: String) -> void:
	var transpiler = Transpiler.new()
	const pyproject_path: String = "res://" + "pyproject" + "." + "toml"
	transpiler.generate_pyproject(pyproject_path, setuptools_min_ver)
	const setup_path = "res://" + "setup" + "." + "py"
	transpiler.generate_setup(setup_path, package_name, author, author_email, project_url, download_url, documentation_url, source_url, tracker_url, description, proj_license)


## Function for transpiling script (by path)
func start(arg: String, stage2: bool, stage3: bool, package_name: String) -> Array:
	var path_end: String = arg.split("=")[1]
	var path: String = "res://" + path_end
	var args = path_end.split(".")
	var c: int = args.size()
	var pathstr: String = ""
	for path_str in args:
		c -= 1
		if c != 0:
			pathstr += path_str + "."
	if pathstr.contains("/.."):
		var paths: Array = pathstr.split("/")
		pathstr = ""
		var index: int = 0
		for path_arg in paths:
			if path_arg == ".." and index > 0:
				var path_size: int = pathstr.length()
				var previous: String = paths[index-1]
				var previous_size: int = previous.length()
				# remove "/"
				pathstr = pathstr.left(path_size-1)
				path_size = pathstr.length()
				# remove previous path
				pathstr = pathstr.left(path_size-previous_size)
			else:
				pathstr += path_arg
				pathstr += "/"
			index += 1
		pathstr = pathstr.left(pathstr.length()-1)
	if stage2:
		const ESCAPE: String = ''
		printraw(ESCAPE + "[2K\r" + "Transpiling " + pathstr + "gd...")
	var path2: String = "res://" + pathstr + "py"
	var transpiler = Transpiler.new()
	transpiler.set_def([])
	var content: String = transpiler.read(path)
	var out: String = transpiler.transpile(content, package_name)
	if transpiler.defs.verbose:
		print(out)
	transpiler.save(path2, out)
	var deps : Array = []
	for dep in transpiler.props.gds_deps:
		deps.append(dep)
	transpiler.props.gds_deps.clear()
	if stage2:
		var application = Application.new()
		application.execute('ruff',['format',pathstr+"py"])
	for dep in deps:
		if dep != deps[0]:
			var path_arr : Array = pathstr.split("/")
			var size : int = path_arr.size()
			path_arr[size-1] = dep.to_lower() + "."
			var result_str = ""
			for string in path_arr:
				result_str += string
				result_str += "/"
			result_str = result_str.left(result_str.length()-1)
			result_str += "gd"
			const comp = false
			transpiler.set_def(start("dep=" + result_str, stage2, comp, package_name))
	if stage3:
		compile(arg)
	return transpiler.get_def()


## Prints Python and Godot Engine version information to console
func version_info() -> void:
	var info: Dictionary = Engine.get_version_info()
	var major: int = info.get("major")
	var minor: int = info.get("minor")
	var patch: int = info.get("patch")
	var status: String = info.get("status")
	var build: String = info.get("build")
	var id: String = info.get("hash")
	var version = Version.new()
	const ESCAPE: String = ''
	const COLOR_RESET: String = "[0m"
	const CYAN: String = "[0;36m";
	const WHITE_BOLD: String = "[1;37m";
	print(CYAN + "GDScript Transpiler " + version.__version__ + ESCAPE + COLOR_RESET + "\n")
	var GDV: String = str(major) + "." + str(minor) + "." + str(patch)
	print(WHITE_BOLD + "Compatible with Godot" + ESCAPE + COLOR_RESET)
	print(GDV + "." + status + "." + build + "." + id.left(9))
	var out: Array = []
	var application = Application.new()
	print(WHITE_BOLD + "Python" + ESCAPE + COLOR_RESET)
	out = application.execute("python3.13", ['-c','import sys;print(sys.version)'])
	print(out[0].split("\n")[0])
	print(WHITE_BOLD + "Nuitka" + ESCAPE + COLOR_RESET)
	out = application.execute("python3.13", ['-c',"from nuitka import Version;print(Version.getNuitkaVersion())"])
	print(out[0].split("\n")[0])
	print(WHITE_BOLD + "Ruff" + ESCAPE + COLOR_RESET)
	out = application.execute('ruff',['version'])
	print(out[0].split("\n")[0].split(" ")[1])
	print(WHITE_BOLD + "Zig" + ESCAPE + COLOR_RESET)
	out = application.execute('zig',['version'])
	print(out[0].split("\n")[0])


## Help function which prints all possible commands
func help() -> void:
	const VER_DESC: String = "show program's version number and exit"
	const HELP_DESC: String = "show this help message and exit"
	const FMT_DESC: String = "transpile and format GDScript files recursively"
	const COMP_DESC: String = "compile GDScript file to binary using Clang/Nuitka"
	const EXP_DESC: String = "experimental option to tokenize GDScript file"
	const SETUP_DESC: String = "generate a setup.py and pyproject.toml file to install Python project"
	const VEC2_DESC: String = "testing Vector2 implementation"
	const PARSER_DESC: String = "running GDScript tests (not working yet)"
	const BENCH_DESC: String = "running benchmark to compare performance"
	const GEN_API: String = "generate API bindings"
	const ESCAPE: String = ''
	const COLOR_RESET: String = "[0m"
	const GREEN: String = "[0;32m";
	const CYAN: String = "[0;36m";
	print("Usage: " + CYAN + "gds" + ESCAPE + COLOR_RESET + " [ " + GREEN + "options" + ESCAPE + COLOR_RESET + " ]" + "\n")
	print("Options:")
	print("  " + GREEN + "version" + ESCAPE + COLOR_RESET + "                           " + VER_DESC)
	print("  " + GREEN + "help" + ESCAPE + COLOR_RESET + "                              " + HELP_DESC)
	print("  " + GREEN + "format" + ESCAPE + COLOR_RESET + "=" + CYAN + "../path/to/file.gd" + ESCAPE + COLOR_RESET + "         " + FMT_DESC)
	print("  " + GREEN + "compile" + ESCAPE + COLOR_RESET + "=" + CYAN + "../path/to/file.gd" + ESCAPE + COLOR_RESET + "        " + COMP_DESC)
	print("  " + GREEN + "exp" + ESCAPE + COLOR_RESET + "=" + CYAN + "../path/to/file.gd" + ESCAPE + COLOR_RESET + "            " + EXP_DESC)
	print("  " + GREEN + "setup" + ESCAPE + COLOR_RESET + "=" + CYAN + "../path/setup.py" + ESCAPE + COLOR_RESET + "            " + SETUP_DESC)
	print("  " + GREEN + "test" + ESCAPE + COLOR_RESET + "=" + CYAN + "vector2" + ESCAPE + COLOR_RESET + "                      " + VEC2_DESC)
	print("  " + GREEN + "test" + ESCAPE + COLOR_RESET + "=" + CYAN + "parser" + ESCAPE + COLOR_RESET + "                       " + PARSER_DESC)
	print("  " + GREEN + "benchmark" + ESCAPE + COLOR_RESET + "                         " + BENCH_DESC)
	print("  " + GREEN + "gen_api" + ESCAPE + COLOR_RESET + "=" + CYAN + "../path/to/godot4" + ESCAPE + COLOR_RESET + "         " + GEN_API)
## Testing benchmark
func run_benchmark() -> void:
	var gdsbin: Dictionary = {"test": {}}
	gdsbin.test.benchmark = Benchmark.new()
	gdsbin.test.benchmark.run()

## GDScript parser tests
func run_parser() -> void:
	var gdsbin: Dictionary = {"test": {}}
	#gdsbin.test.advanced_expression_matching = Advanced_expression_matching.new()
	#gdsbin.test.advanced_expression_matching.test()
	#gdsbin.test.arrays = Arrays.new()
	#gdsbin.test.arrays.test()
	gdsbin.test.arrays_dictionaries_nested_const = Arrays_dictionaries_nested_const.new()
	gdsbin.test.arrays_dictionaries_nested_const.test()
	#gdsbin.test.basic_expression_matching = Basic_expression_matching.new()
	#gdsbin.test.basic_expression_matching.test()
	#gdsbin.test.bitwise_operators = Bitwise_operators.new()
	#gdsbin.test.bitwise_operators.test()
	gdsbin.test.concatenation = Concatenation.new()
	gdsbin.test.concatenation.test()
	#gdsbin.test.constants = Constants.new()
	#gdsbin.test.constants.test()
	#gdsbin.test.dictionaries = Dictionaries.new()
	#gdsbin.test.dictionaries.test()
	#gdsbin.test.dictionary_lua_style = Dictionary_lua_style.new()
	#gdsbin.test.dictionary_lua_style.test()
	#gdsbin.test.dictionary_mixed_syntax = Dictionary_mixed_syntax.new()
	#gdsbin.test.dictionary_mixed_syntax.test()
	#gdsbin.test.dollar_and_percent_get_node = Dollar_and_percent_get_node.new()
	#gdsbin.test.dollar_and_percent_get_node.test()
	#gdsbin.test.dollar_node_paths = Dollar_node_paths.new()
	#gdsbin.test.dollar_node_paths.test()
	#gdsbin.test.enums = Enums.new()
	#gdsbin.test.enums.test()
	#gdsbin.test.export_variable = Export_variable.new()
	#gdsbin.test.export_variable.test()
	#gdsbin.test.float_notation = Float_notation.new()
	#gdsbin.test.float_notation.test()
	#gdsbin.test.for_range = For_range.new()
	#gdsbin.test.for_range.test()
	gdsbin.test.function_default_parameter_type_inference = Function_default_parameter_type_inference.new()
	gdsbin.test.function_default_parameter_type_inference.test()
	#gdsbin.test.function_many_parameters = Function_many_parameters.new()
	#gdsbin.test.function_many_parameters.test()
	#gdsbin.test.if_after_lambda = If_after_lambda.new()
	#gdsbin.test.if_after_lambda.test()
	#gdsbin.test.ins = Ins.new()
	#gdsbin.test.ins.test()
	#gdsbin.test.lambda_callable = Lambda_callable.new()
	#gdsbin.test.lambda_callable.test()
	#gdsbin.test.lambda_capture_callable = Lambda_capture_callable.new()
	#gdsbin.test.lambda_capture_callable.test()
	#gdsbin.test.lambda_default_parameter_capture = Lambda_default_parameter_capture.new()
	#gdsbin.test.lambda_default_parameter_capture.test()
	#gdsbin.test.lambda_named_callable = Lambda_named_callable.new()
	#gdsbin.test.lambda_named_callable.test()
	gdsbin.test.matches = Matches.new()
	gdsbin.test.matches.test()
	gdsbin.test.match_bind_unused = Match_bind_unused.new()
	gdsbin.test.match_bind_unused.test()
	#gdsbin.test.match_dictionary = Match_dictionary.new()
	#gdsbin.test.match_dictionary.test()
	gdsbin.test.match_multiple_patterns_with_array = Match_multiple_patterns_with_array.new()
	gdsbin.test.match_multiple_patterns_with_array.test()
	#gdsbin.test.match_multiple_variable_binds_in_pattern = Match_multiple_variable_binds_in_pattern.new()
	#gdsbin.test.match_multiple_variable_binds_in_pattern.test()
	gdsbin.test.multiline_arrays = Multiline_arrays.new()
	gdsbin.test.multiline_arrays.test()
	#gdsbin.test.multiline_dictionaries = Multiline_dictionaries.new()
	#gdsbin.test.multiline_dictionaries.test()
	#gdsbin.test.multiline_if = Multiline_if.new()
	#gdsbin.test.multiline_if.test()
	#gdsbin.test.multiline_strings = Multiline_strings.new()
	#gdsbin.test.multiline_strings.test()
	#gdsbin.test.multiline_vector = Multiline_vector.new()
	#gdsbin.test.multiline_vector.test()
	gdsbin.test.nested_arithmetic = Nested_arithmetic.new()
	gdsbin.test.nested_arithmetic.test()
	gdsbin.test.nested_array = Nested_array.new()
	gdsbin.test.nested_array.test()
	#gdsbin.test.nested_dictionary = Nested_dictionary.new()
	#gdsbin.test.nested_dictionary.test()
	gdsbin.test.nested_function_calls = Nested_function_calls.new()
	gdsbin.test.nested_function_calls.test()
	#gdsbin.test.nested_if = Nested_if.new()
	#gdsbin.test.nested_if.test()
	#gdsbin.test.nested_match = Nested_match.new()
	#gdsbin.test.nested_match.test()
	gdsbin.test.nested_parentheses = Nested_parentheses.new()
	gdsbin.test.nested_parentheses.test()
	#gdsbin.test.number_separators = Number_separators.new()
	#gdsbin.test.number_separators.test()
	gdsbin.test.operator_assign = Operator_assign.new()
	gdsbin.test.operator_assign.test()
	#gdsbin.test.property_setter_getter = Property_setter_getter.new()
	#gdsbin.test.property_setter_getter.test()
	#gdsbin.test.semicolon_as_end_statement = Semicolon_as_end_statement.new()
	#gdsbin.test.semicolon_as_end_statement.test()
	gdsbin.test.semicolon_as_terminator = Semicolon_as_terminator.new()
	gdsbin.test.semicolon_as_terminator.test()
	#gdsbin.test.signal_declaration = Signal_declaration.new()
	#gdsbin.test.signal_declaration.test()
	#gdsbin.test.static_typing = Static_typing.new()
	#gdsbin.test.static_typing.test()
	#gdsbin.test.string_formatting = String_formatting.new()
	#gdsbin.test.string_formatting.test()
	gdsbin.test.str_preserves_case = Str_preserves_case.new()
	gdsbin.test.str_preserves_case.test()
	gdsbin.test.trailing_comma_in_function_args = Trailing_comma_in_function_args.new()
	gdsbin.test.trailing_comma_in_function_args.test()
	#gdsbin.test.truthiness = Truthiness.new()
	#gdsbin.test.truthiness.test()
	gdsbin.test.typed_arrays = Typed_arrays.new()
	gdsbin.test.typed_arrays.test()
	#gdsbin.test.variable_declaration = Variable_declaration.new()
	#gdsbin.test.variable_declaration.test()
	gdsbin.test.whiles = Whiles.new()
	gdsbin.test.whiles.test()

## Testing Vector2 implementation
func run_vector2() -> void:
	var vector2 = VECTOR2.new()
	vector2.x = 3
	vector2.y = 5
	print("x -> " + str(vector2.x))
	print("y -> " + str(vector2.y))
	print("angle() -> " + str(vector2.angle(vector2)))
	var vector2_res = vector2.from_angle(30)
	print("from_angle(30) -> " + "(" + str(vector2_res.x) + ", " + str(vector2_res.y) + ")")
	print("vec_length() -> " + str(vector2.vec_length(vector2)))
	print("length_squared() -> " + str(vector2.length_squared(vector2)))
	var vector2_res2 = vector2.normalized(vector2)
	print("normalized() -> " + "(" + str(vector2_res2.x) + ", " + str(vector2_res2.y) + ")")
	print("is_normalized() -> " + str(vector2_res2.is_normalized(vector2)))
	print("distance_to() -> " + str(vector2.distance_to(vector2, vector2)))
	print("distance_squared_to() -> " + str(vector2.distance_squared_to(vector2, vector2)))
	print("angle_to() -> " + str(vector2.angle_to(vector2, vector2)))
	print("angle_to_point() -> " + str(vector2.angle_to_point(vector2, vector2)))
	print("dot() -> " + str(vector2.dot(vector2, vector2)))
	print("cross() -> " + str(vector2.cross(vector2, vector2)))
	var vec_rot = vector2.rotated(vector2, 1)
	print("rotated() -> " + "(" + str(vec_rot.x) + ", " + str(vec_rot.y) + ")")
	var vec_proj = vector2.project(vector2, vector2)
	print("project() -> " + "(" + str(vec_proj.x) + ", " + str(vec_proj.y) + ")")
	var vec_lim = vector2.limit_length(vector2, 2, vector2)
	print("limit_length() -> " + "(" + str(vec_lim.x) + ", " + str(vec_lim.y) + ")")
