## GDScript Transpiler Properties Class

# Autogenerated class (gen_api)
# See https://raw.githubusercontent.com/godotengine/godot-cpp/master/gdextension/extension_api.json

class_name Variant_operator

const OP_EQUAL: int = 0
const OP_NOT_EQUAL: int = 1
const OP_LESS: int = 2
const OP_LESS_EQUAL: int = 3
const OP_GREATER: int = 4
const OP_GREATER_EQUAL: int = 5
const OP_ADD: int = 6
const OP_SUBTRACT: int = 7
const OP_MULTIPLY: int = 8
const OP_DIVIDE: int = 9
const OP_NEGATE: int = 10
const OP_POSITIVE: int = 11
const OP_MODULE: int = 12
const OP_POWER: int = 13
const OP_SHIFT_LEFT: int = 14
const OP_SHIFT_RIGHT: int = 15
const OP_BIT_AND: int = 16
const OP_BIT_OR: int = 17
const OP_BIT_XOR: int = 18
const OP_BIT_NEGATE: int = 19
const OP_AND: int = 20
const OP_OR: int = 21
const OP_XOR: int = 22
const OP_NOT: int = 23
const OP_IN: int = 24
const OP_MAX: int = 25
