## GDScript Transpiler Properties Class

# Autogenerated class (gen_api)
# See https://raw.githubusercontent.com/godotengine/godot-cpp/master/gdextension/extension_api.json

class_name Variant_type

const TYPE_NIL: int = 0
const TYPE_BOOL: int = 1
const TYPE_INT: int = 2
const TYPE_FLOAT: int = 3
const TYPE_STRING: int = 4
const TYPE_VECTOR2: int = 5
const TYPE_VECTOR2I: int = 6
const TYPE_RECT2: int = 7
const TYPE_RECT2I: int = 8
const TYPE_VECTOR3: int = 9
const TYPE_VECTOR3I: int = 10
const TYPE_TRANSFORM2D: int = 11
const TYPE_VECTOR4: int = 12
const TYPE_VECTOR4I: int = 13
const TYPE_PLANE: int = 14
const TYPE_QUATERNION: int = 15
const TYPE_AABB: int = 16
const TYPE_BASIS: int = 17
const TYPE_TRANSFORM3D: int = 18
const TYPE_PROJECTION: int = 19
const TYPE_COLOR: int = 20
const TYPE_STRING_NAME: int = 21
const TYPE_NODE_PATH: int = 22
const TYPE_RID: int = 23
const TYPE_OBJECT: int = 24
const TYPE_CALLABLE: int = 25
const TYPE_SIGNAL: int = 26
const TYPE_DICTIONARY: int = 27
const TYPE_ARRAY: int = 28
const TYPE_PACKED_BYTE_ARRAY: int = 29
const TYPE_PACKED_INT32_ARRAY: int = 30
const TYPE_PACKED_INT64_ARRAY: int = 31
const TYPE_PACKED_FLOAT32_ARRAY: int = 32
const TYPE_PACKED_FLOAT64_ARRAY: int = 33
const TYPE_PACKED_STRING_ARRAY: int = 34
const TYPE_PACKED_VECTOR2_ARRAY: int = 35
const TYPE_PACKED_VECTOR3_ARRAY: int = 36
const TYPE_PACKED_COLOR_ARRAY: int = 37
const TYPE_PACKED_VECTOR4_ARRAY: int = 38
const TYPE_MAX: int = 39
