name: "godot-ci download"
on:
  workflow_dispatch

env:
  GODOT_VERSION: "4.0"
  RELEASE_NAME: beta1

jobs:
  export-templates:
    name: Templates Export
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          curl https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}${SUBDIR}/${RELEASE_NAME}/Godot_v${GODOT_VERSION}-${RELEASE_NAME}_linux.x86_64.zip > Godot_linux.x86_64.zip
          curl https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}${SUBDIR}/${RELEASE_NAME}/Godot_v${GODOT_VERSION}-${RELEASE_NAME}_win64.exe.zip > Godot_win64.exe.zip
          curl https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}${SUBDIR}/${RELEASE_NAME}/Godot_v${GODOT_VERSION}-${RELEASE_NAME}_export_templates.tpz > Godot_export_templates.tpz
          curl https://codeberg.org/attachments/78a8cfa9-db1d-4288-b057-d5b4c3475f23 > godot.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Godot_linux.x86_64.zip
          path: Godot_linux.x86_64.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Godot_win64.exe.zip
          path: Godot_win64.exe.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Godot_export_templates.tpz
          path: Godot_export_templates.tpz
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Godot.zip
          path: Godot.zip