name: 🐧 Linux Upload
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["🐧 Linux Build"]
    types:
      - completed

jobs:
  build-linux:
    runs-on: "ubuntu-latest"
    name: Linux itch.io Upload
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: Linux Build
          path: build/main.bin

      - name: Upload to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: gdscript-transpiler-bin
          ITCH_USER: linuxusergd
          PACKAGE: build/main.bin