name: 🐧 Linux Build
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Template"]
    types:
      - completed

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-linux
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: "ubuntu-latest"
    name: ${{ matrix.name }}
    steps:
      - name: Update script
        run: |
          wget https://gist.githubusercontent.com/LinuxUserGD/73d8e030a44eb7f91bdeaea96a321f6d/raw/main.py
          wget https://gist.githubusercontent.com/LinuxUserGD/73d8e030a44eb7f91bdeaea96a321f6d/raw/requirements.txt

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Python Script
        run: |
          python main.py

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@v0.4
        with:
          script-name: main.py
          onefile: true
          enable-plugins: anti-bloat

      - name: Upload main.bin
        uses: actions/upload-artifact@v3
        with:
          name: Linux Build
          path: build/main.bin
