name: 🍎 macOS Upload
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["🍎 macOS Build"]
    types:
      - completed

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    name: macOS itch.io Upload
    steps:
      - uses: actions/checkout@master
      - name: Download artifact from build
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: LinuxUserGD/gdscript-transpiler-bin
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: MacOS Build
          rename: macOS.zip
          wait_seconds: 10

      - name: Upload to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac
          ITCH_GAME: gdscript-transpiler-bin
          ITCH_USER: linuxusergd
          PACKAGE: macOS.zip