name: Template Build
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Template"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GODOT_VERSION: "4.0"
  RELEASE_NAME: beta14

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: ${{ matrix.name }}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2.5.0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install urllib3

      - name: Download artifact from build
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: LinuxUserGD/gdscript-transpiler-bin
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: Godot_export_templates.tpz
          rename: Godot_export_templates.tpz.zip
          wait_seconds: 20

      - name: Extract Godot_export_templates.tpz
        run: |
          unzip Godot_export_templates.tpz.zip
          unzip Godot_export_templates.tpz

      - name: Download artifact from build
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: LinuxUserGD/gdscript-transpiler-bin
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: Godot_linux.x86_64.zip
          rename: Godot_linux.x86_64.zip.zip
          wait_seconds: 20

      - name: Extract Godot_win64.exe.zip
        run: |
          unzip Godot_linux.x86_64.zip.zip
          unzip Godot_linux.x86_64.zip

      - name: Setup
        run: |
          echo "${GODOT_VERSION}"
          echo "${RELEASE_NAME}"
          mv "Godot_v${{ env.GODOT_VERSION }}-${{ env.RELEASE_NAME }}_linux.x86_64" godot
          mkdir /home/user/.local/share/godot/export_templates/${GODOT_VERSION}.${RELEASE_NAME}
          ls
          cd templates
          mv version.txt /home/user/.local/share/godot/export_templates/${GODOT_VERSION}.${RELEASE_NAME}
          mv web_release.zip /home/user/.local/share/godot/Godot\export_templates/${GODOT_VERSION}.${RELEASE_NAME}
          mv web_debug.zip /home/user/.local/share/godot/export_templates/${GODOT_VERSION}.${RELEASE_NAME}
          mv web_dlink_release.zip /home/user/.local/share/godot/export_templates/${GODOT_VERSION}.${RELEASE_NAME}
          mv web_dlink_debug.zip /home/user/.local/share/godot/export_templates/${GODOT_VERSION}.${RELEASE_NAME}
          cd ..
          curl -L --output full-size.html --url https://raw.githubusercontent.com/godotengine/godot/master/misc/dist/html/full-size.html
          mkdir dist
          mkdir temp

      - name: Run file with timeout
        timeout-minutes: 2 # Times out after 2 minutes
        run: |
          python .github/workflows/godot.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: html5
          path: dist
