name: Upload
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Template"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Linux itch.io Upload
    outputs:
      status: ${{ steps.early.outputs.status }}
    steps:
      - name: Download artifact from build
        uses: bettermarks/action-artifact-download@0.4.0
        with:
          repo: LinuxUserGD/gdscript-transpiler-bin
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: Linux Build
          rename: linux.zip
          wait_seconds: 20

      - name: Download artifact from build
        uses: bettermarks/action-artifact-download@0.4.0
        with:
          repo: LinuxUserGD/gdscript-transpiler-bin
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: MacOS Build
          rename: macOS.zip
          wait_seconds: 20

      - name: Download artifact from build
        uses: bettermarks/action-artifact-download@0.4.0
        with:
          repo: LinuxUserGD/gdscript-transpiler-bin
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: Windows Build
          rename: windows.zip
          wait_seconds: 20

      - name: Extracting linux.zip
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install unzip
          unzip linux.zip
          rm linux.zip

      - name: Uploading linux binary
        uses: yeslayla/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: gdscript-transpiler-bin
          ITCH_USER: linuxusergd
          PACKAGE: gds

      - name: Extracting macOS.zip
        shell: bash
        run: |
          rm -rf gds
          unzip macOS.zip
          rm macOS.zip

      - name: Uploading macOS binary
        uses: yeslayla/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac
          ITCH_GAME: gdscript-transpiler-bin
          ITCH_USER: linuxusergd
          PACKAGE: gds

      - name: Extracting windows.zip
        shell: bash
        run: |
          rm -rf gds
          unzip windows.zip
          rm windows.zip

      - name: Uploading windows binary
        uses: yeslayla/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: gdscript-transpiler-bin
          ITCH_USER: linuxusergd
          PACKAGE: gds.exe
