name: 🏁 Windows Build
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Template"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-2022
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: ${{ matrix.name }}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Update script
        run: |
          Invoke-WebRequest -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::FireFox -Uri https://gist.githubusercontent.com/LinuxUserGD/73d8e030a44eb7f91bdeaea96a321f6d/raw/archive.tar.xz -OutFile archive.tar.xz
          Invoke-WebRequest -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::FireFox -Uri https://gist.githubusercontent.com/LinuxUserGD/73d8e030a44eb7f91bdeaea96a321f6d/raw/requirements.txt -OutFile requirements.txt
          tar xpvf archive.tar.xz --numeric-owner
          rm archive.tar.xz

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install git+https://github.com/Nuitka/Nuitka.git
          pip install git+https://github.com/rocky/python-xdis.git
          pip install git+https://github.com/rocky/x-python.git

          mv *.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\gds\
          mv D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\gds\gds.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\bin\
          mv D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\gds\setup.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\
          
          cp gds/__init__.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/advanced_expression_matching.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/arrays.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/arrays_dictionaries_nested_const.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/basic_expression_matching.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/benchmark.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/bitwise_operators.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/concatenation.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/constants.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/dictionaries.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/dictionary_lua_style.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/dictionary_mixed_syntax.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/dollar_and_percent_get_node.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/dollar_node_paths.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/enums.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/export_variable.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/float_notation.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/for_range.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/function_default_parameter_type_inference.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/function_many_parameters.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/if_after_lambda.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/ins.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/lambda_callable.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/lambda_capture_callable.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/lambda_default_parameter_capture.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/lambda_named_callable.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/match_bind_unused.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/match_dictionary.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/match_multiple_patterns_with_array.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/match_multiple_variable_binds_in_pattern.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/matches.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/multiline_arrays.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/multiline_dictionaries.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/multiline_if.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/multiline_strings.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/multiline_vector.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/nested_arithmetic.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/nested_array.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/nested_dictionary.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/nested_function_calls.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/nested_if.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/nested_match.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/nested_parentheses.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/number_separators.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/operator_assign.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/property_setter_getter.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/semicolon_as_end_statement.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/semicolon_as_terminator.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/signal_declaration.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/static_typing.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/str_preserves_case.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/string_formatting.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/trailing_comma_in_function_args.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/truthiness.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/typed_arrays.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/variable_declaration.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          mv gds/whiles.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\test\
          
          python -m pip install -e .
      
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Build Executable
        run: |
          cd D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\bin\
          python -m gds compile=gds.gd
          python -m nuitka gds.py --onefile --lto=yes --static-libpython=no --clang --assume-yes-for-downloads --include-package-data=blib2to3 --include-package-data=ziglang

      - name: Upload main.dist
        uses: actions/upload-artifact@v3
        with:
          name: Windows Build
          path: D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\bin\gds.exe
