name: 🏁 Windows Build
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Template"]
    types:
      - completed

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-2022
    name: ${{ matrix.name }}
    steps:
      - name: Update script
        run: |
          Invoke-WebRequest https://gist.githubusercontent.com/LinuxUserGD/73d8e030a44eb7f91bdeaea96a321f6d/raw/__main__.py -OutFile '__main__.py'
          Invoke-WebRequest https://gist.githubusercontent.com/LinuxUserGD/73d8e030a44eb7f91bdeaea96a321f6d/raw/transpiler.py -OutFile 'transpiler.py'
          Invoke-WebRequest https://gist.githubusercontent.com/LinuxUserGD/73d8e030a44eb7f91bdeaea96a321f6d/raw/props.py -OutFile 'props.py'
          Invoke-WebRequest https://gist.githubusercontent.com/LinuxUserGD/73d8e030a44eb7f91bdeaea96a321f6d/raw/vector2.py -OutFile 'vector2.py'
          Invoke-WebRequest https://gist.githubusercontent.com/LinuxUserGD/73d8e030a44eb7f91bdeaea96a321f6d/raw/version.py -OutFile 'version.py'
          Invoke-WebRequest https://gist.githubusercontent.com/LinuxUserGD/73d8e030a44eb7f91bdeaea96a321f6d/raw/audio.py -OutFile 'audio.py'
          Invoke-WebRequest https://gist.githubusercontent.com/LinuxUserGD/73d8e030a44eb7f91bdeaea96a321f6d/raw/requirements.txt -OutFile 'requirements.txt'
          Invoke-WebRequest https://raw.githubusercontent.com/LinuxUserGD/GDScript2PythonTranspiler/dev/gdscript-transpiler-bin/__main__.gd -OutFile '__main__.gd'
          Invoke-WebRequest https://raw.githubusercontent.com/LinuxUserGD/GDScript2PythonTranspiler/dev/gdscript-transpiler-bin/transpiler.gd -OutFile 'transpiler.gd'
          Invoke-WebRequest https://raw.githubusercontent.com/LinuxUserGD/GDScript2PythonTranspiler/dev/gdscript-transpiler-bin/props.gd -OutFile 'props.gd'
          Invoke-WebRequest https://raw.githubusercontent.com/LinuxUserGD/GDScript2PythonTranspiler/dev/gdscript-transpiler-bin/vector2.gd -OutFile 'vector2.gd'
          Invoke-WebRequest https://raw.githubusercontent.com/LinuxUserGD/GDScript2PythonTranspiler/dev/gdscript-transpiler-bin/version.gd -OutFile 'version.gd'
          Invoke-WebRequest https://raw.githubusercontent.com/LinuxUserGD/GDScript2PythonTranspiler/dev/gdscript-transpiler-bin/audio.gd -OutFile 'audio.gd'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install git+https://github.com/rocky/python-xdis.git
          pip install git+https://github.com/rocky/x-python.git

      - name: Generate Python Script
        run: |
          python __main__.py path=transpiler.gd
          python __main__.py path=props.gd
          python __main__.py path=vector2.gd
          python __main__.py path=version.gd
          python __main__.py path=audio.gd
          python __main__.py path=__main__.gd
          mv __main__.py gds
      
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Build Executable
        uses: LinuxUserGD/Nuitka-Action@v0.5
        with:
          script-name: gds
          onefile: true
          clang: true

      - name: Upload main.dist
        uses: actions/upload-artifact@v3
        with:
          name: Windows Build
          path: build/gds.exe
