name: 🏁 Windows Build
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Template"]
    types:
      - completed

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-2022
    name: ${{ matrix.name }}
    steps:
      - name: Update script
        run: |
          git clone https://gist.github.com/73d8e030a44eb7f91bdeaea96a321f6d.git
          cd 73d8e030a44eb7f91bdeaea96a321f6d
          mv * ..
          cd ..

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install git+https://github.com/Nuitka/Nuitka.git
          pip install git+https://github.com/rocky/python-xdis.git
          pip install git+https://github.com/rocky/x-python.git
          mkdir gds
          mkdir bin
          mv *.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\gds\
          mv *.gd D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\gds\
          mv D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\gds\gds.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\bin\
          mv D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\gds\gds.gd D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\bin\
          mv D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\gds\setup.py D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\
          python -m pip install -e .
      
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Build Executable
        run: |
          cd D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\bin\
          python -m gds compile=gds.gd
          python -m nuitka gds.py --onefile --lto=yes --static-libpython=no --clang --assume-yes-for-downloads

      - name: Upload main.dist
        uses: actions/upload-artifact@v3
        with:
          name: Windows Build
          path: D:\a\gdscript-transpiler-bin\gdscript-transpiler-bin\bin\gds.exe
