name: 🏁 Windows Upload
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["🏁 Windows Build"]
    types:
      - completed

jobs:
  build-linux:
    runs-on: "ubuntu-latest"
    name: Windows itch.io Upload
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: Windows Build
          path: build/main.exe

      - name: Upload to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: gdscript-transpiler-bin
          ITCH_USER: linuxusergd
          PACKAGE: build/main.exe